# Generated by Django 3.0 on 2019-12-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Category', verbose_name='Category'),
        ),
    ]
