# Generated by Django 3.0 on 2019-12-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_title',
            new_name='title',
        ),
    ]
