# Generated by Django 3.0 on 2019-12-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20191231_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='forum/static/forum/assets/profile_images/default_user_icon.png', upload_to='forum/static/forum/assets/profile_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
