# Generated by Django 3.0 on 2019-12-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20191231_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='forum/static/forum/assets/profile_images/default_user_icon.png', upload_to='forum/static/forum/assets/profile_images/'),
        ),
    ]
