# Generated by Django 3.0 on 2020-01-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20200101_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='posts',
            new_name='posts_count',
        ),
    ]
